language: java
notifications:
  slack:
    secure: R9rabV1tVHFE6+3EyNeM5FxPtcHA5kJG+ta1NsbY8jhkoTB/JC+/Cm7TAFZrIbqYJrbKgaAnimDyhb8vnyTYT4zXrIZyulOaKHhf75rueFG0zcg3I1N0DUCvgTmgnVhleFnlRLfNlWpULjHLgNn379Rvn3/lFEQkx8hpLrZd6i+zsjFhePIRLLkxmrCYoNjeQ7yjtBOX6aJU2PfhbBnRafC36m4FuDJWtGO0sJRu9soN5fJCuSleqz9/KliYR4jtjO6bWqOrXvFWnLn8wg1dIjQKpp4+qgkd2eOPd6dWHl2y93nT1QXYW7TOLjLGd6CwC/lQAVufSv9yz4fze5YMLIKnAxWcCfaPY7XQBMliKKsTb3JtZ2n2HAPK1+GOzoMZE3StUs+ID9d2+7RJaXDQfOfHjfUteya8Cz88H6KEZ5wML815S6oDPDKxIMjUq+R6W3wi0lbkO14F5jo86nu3SxwAOSREemdRzpBIeXJtCLAJhXdE1n9EqUH03NVehNMKuQtwlQEoMw3MIzWkg4JjP7XGtqWtX1X72Qc0dIDcgWNJwrVEIWk4hDzFQU862tIfLRUWEveJledNJ44AAq5O6K6MRG3DQd3ikR/uWD4aCDgQER+9DOwvqNPOvrMbAm346eQki7X13Co0yCyhL01Q6DasHpnOkG4Cg1osO4iz4S0=
deploy:
  provider: releases
  api_key:
    secure: UKSnmvAQbhNIjviOlylmmNR0ACZnlhBN1WHk8vnXnrU9OVSqvhFEUDbt/i5wAlM7hcS3tz66unQkijw/r6j0yJW2QauFAoC0Pz1KF612km0eT3lEFZblXvrIzbzS65hCeX9F68V4oyrIGFp0uj2H6x82CjeELrzoMjmLLN5fkBHxeO+eI2xebV8NxQpQuAqvA5QtuhtLLgHxNyRl6XkBk4UKAQKJ7u1RGJjOtFLLNNMTBL9gJvDGhOVFfaoRggq+EvqI12wN1cyc0JAlO4lCv5CulmdMRtiuV58R6zOYsQl1K7s1MJvcuHl8+DHgAjhn6hcDCio0w4aQyXqacwoh8/FfawWS720r0x6TM7OV09JTTVZd4anBWBgCR8ZfTzwCjVy4sfAIbG+DlfBMBhb56iN5KRWCFKaGfqhVKB75bzH6zPvQpKJpS8EO/VRupDzWs8VN8nri8b9DB9c95FI62N4aDxWY7iqbZRXpMl1VMg5EVgaugGnHccn81T2sMcvUz9FqivlP7FK6NpdUfioW8c5d8EDC3BqJjfWdt7w4VWlhuqRKRwIhw9TYsv4fTGeog5enHoecfxMFnjazfCy29oDnTB9o58Hoe3CjjyaFcyL99Y+9Xb57TPO0hD8SLSl6aHAI44dY11GusnwAv11Kg4EUShNlILyOXaBceejDjx8=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-nginx-plus-plugin
