language: java
notifications:
  slack:
    secure: R9rabV1tVHFE6+3EyNeM5FxPtcHA5kJG+ta1NsbY8jhkoTB/JC+/Cm7TAFZrIbqYJrbKgaAnimDyhb8vnyTYT4zXrIZyulOaKHhf75rueFG0zcg3I1N0DUCvgTmgnVhleFnlRLfNlWpULjHLgNn379Rvn3/lFEQkx8hpLrZd6i+zsjFhePIRLLkxmrCYoNjeQ7yjtBOX6aJU2PfhbBnRafC36m4FuDJWtGO0sJRu9soN5fJCuSleqz9/KliYR4jtjO6bWqOrXvFWnLn8wg1dIjQKpp4+qgkd2eOPd6dWHl2y93nT1QXYW7TOLjLGd6CwC/lQAVufSv9yz4fze5YMLIKnAxWcCfaPY7XQBMliKKsTb3JtZ2n2HAPK1+GOzoMZE3StUs+ID9d2+7RJaXDQfOfHjfUteya8Cz88H6KEZ5wML815S6oDPDKxIMjUq+R6W3wi0lbkO14F5jo86nu3SxwAOSREemdRzpBIeXJtCLAJhXdE1n9EqUH03NVehNMKuQtwlQEoMw3MIzWkg4JjP7XGtqWtX1X72Qc0dIDcgWNJwrVEIWk4hDzFQU862tIfLRUWEveJledNJ44AAq5O6K6MRG3DQd3ikR/uWD4aCDgQER+9DOwvqNPOvrMbAm346eQki7X13Co0yCyhL01Q6DasHpnOkG4Cg1osO4iz4S0=
deploy:
  provider: releases
  api_key:
    secure: G77IpMfVQK3cYn0067ZktKBkev/e4NFpO9SamFDtPgtA6ST4Hd22CaveBrdP1ATToqZWiB1thIgtk35zfkTEKw76CqfiRPZLhfzaGTqGtehFGo6aaujSHJrAiPc++tr0FLt/W2oAiYgo6jr5D8kr31PYaSoOteDaaGkmQieGbcSALJUxGMddVwJ+OkKH8jdW3MkXTIYX62eI0BjWaz8lJzxgGBXO46+UjA+QyrTlWNZB+zQwCuk9+3c3YFLKFdjqnu4K2WAklJXz/rUMFzX3dit7uZUg/9exIe0AwqHkhoIxunYqWcbTCLZH0orGPrsl7rNAEkxodTsTBLFKSaAAKV7UH5gMdpuydMov7rRmL1vIFYUsDEKB9//ZdmEbV/KFra34GJ/q5GxTKTJVhBKxngDm9t9CCBV+IXYO4ps7h9ERifDNRm2YPO2pWi69B1v6wgPNr4HLzzONjQa6CabfWM6Vy1r9S0/aPaOIQsgzGQISiu8dF+1OqowjAOlldAABJHvPII5hriJpptYqYreHJqA1khcM+APixvsGyio/v77Lk0Y0fuYT4D6JMaiFx3J3W+xdYMrNiZXzLq2rKjTfShNfYUC0eJZ+o38mtyC9ir2VnwRPU5Y9rgarNotSqPhilM40gX6o8rb6D/pp0NjAYEWHz9/bmq+FDjMiuCdU2cE=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-nginx-plus-plugin
